### ISSUE TITLE
As developer, I want more details in the API spec and documentation

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#106]
The documentation and the API spec should provide more information about history specifically AND all `help_text` for all fields should be usefull.

- [x] `versions` in Objecttypes API needs helptext
- [x] Objecttypes API general intro (like Objects API introduction)
- [x] Objecttypes API section about versions, how it works with publishing (like Objects API history)
- [x] Objecttypes API section about schema validation (with link to JSON schema).

- [x] `records` in Objects API needs helptext
- ~~Objects API section about how an object is validated against the objecttype (and its version).~~
- [x] Objects API `Content-Crs`, `Accept-Crs`-headers, `url`-helptext are Dutch. Can we make it English? (probably the string is in Dutch in vng-api-common. We can make it into a translatable string)

**Comment by annashamray** [comment]
>  Objects API section about how an object is validated against the objecttype (and its version).

I think it is already included in the OAS https://github.com/maykinmedia/objects-api/blob/020de0a47bb3f6284f6c279fb3025032a5e1b500/src/objects/api/schema.py#L16

**Comment by joeribekker** [comment]
Oops, I did that this morning since I was inspired by your texts :)

**Comment by annashamray** [comment]
> Objects API Content-Crs, Accept-Crs-headers, url-helptext are Dutch. Can we make it English? (probably the string is in Dutch in vng-api-common. We can make it into a translatable string)

The `drf_yasg` inspector for "Content-Crs" and "Accept-Crs" is already included in the Objects API, the description is in Dutch because of copy-paste from `vng_api_common`. I fixed it in the PR. 
The `drf_yasg` inspector for "url" is located in `vng_api_common` and has a non-translatable description in Dutch. I don't want to change it there since I want to stop using `drf_yasg` in Objects API in the nearest future. So the quick win was to create the required inspector in the Objects API repo
