### ISSUE TITLE
As developer, I want a better error message when my components are not correctly configured

### ISSUE THREAD

**Issue by andyverberne** [maykinmedia/objects-api#141]
Original title: Object POST geeft internal server error: Exception Value: 'NoneType' object has no attribute 'retrieve'

POST van object (/api/v1/objects) 
```
{
  "record": {
    "data": {
      "categorie": "Hoofd 1",
      "melder": {
        "e-mailadres": "abcd@bcd.com"
      },
      "toelichting": "Test"
    },
    "startAt": "2021-01-21",
    "typeVersion": 2
  },
  "type": "http://object-registratie.development-public-service-platform.net/objecttypes/api/v1/objecttypes/d7775e82-9c47-4093-82a9-3dcc0d1c8a42"
}
```

geeft een internal server error: [response.txt](https://github.com/maykinmedia/objects-api/files/5860407/response.txt)

**Comment by andyverberne** [comment]
Ik heb het probleem inmiddels opgelost. Na wat speuren in de source zag ik dat de API connectie naar objecttypes niet goed was geconfigureerd. Ik moest echter wel even speuren voordat ik dat gevonden had. 

Ik denk dat het een goed idee zou zijn wanneer de foutboodschap beter zou omschrijven wat het probleem is. En dat de configuratie van het objecttypes api prominenter aanwezikan zijn.

**Comment by joeribekker** [comment]
Ik open em weer, met de insteek dat we een goede foutmelding toevoegen.

**Comment by joeribekker** [comment]
We figured out that this was caused by not having Objecttypes-service configured.

This issues was partially caused by Services not being in the menu making it hard to figure out this needed to be done. Documentation has since been added, the menu item was added and when still doing this, you will get an error due to the refactoring of how permissions work.
