### ISSUE TITLE
As user I don't want the demo data to be loaded by default

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#215]
Solution: We can place the demodata in a fixtures/demo folder wo it wont be loaded by docker_start.sh

Please adjust documentation to reflect that you will need to load the demo data manually from that folder.

**Comment by dariomory** [comment]
This was misunderstood. The files must be in the fixtures folder but it is unrelated to the source code folder, because it must be at the root of the project in order to be loaded.

The `default_admin_index.json` fixture found in the folder is auto-loading as a result of the `post_migrate` signal.

Closing this issue.
