### ISSUE TITLE
As developer, I want to filter on **any** data-attribute

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#34]

**Comment by annashamray** [comment]
For this issue I can see two options for how to implement it: 
1. Create our own DSL (similar to GraphQL or Elastic) and use POST requests with search body, we can reuse `search` endpoint for this purpose
2. For simple searches use query parameter in the URL, which value includes data attribute name, operator and value

In #87 I've implemented the 2nd option since it's the easiest one. If its limitations are crucial we could always switch to the 1st option and creating own GraphQL :)

**Comment by annashamray** [comment]
Implementation was hugely inspired by camunda REST API (https://docs.camunda.org/manual/7.11/reference/rest/task/get-query/ `taskVariables` parameter)
